version: "3.7"

services:
  db:
    image: postgres:14.3
    restart: unless-stopped
    ports:
      - "5432:5432"
    container_name: content-boost-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data
      - ./postgres:/var/lib/postgresql/data

volumes:
  database:
